name: bonus4
description: A telegram bot for bonus lab.
version: 0.0.1

environment:
  sdk: ^3.4.0

dependencies:
  hive: ^2.2.3
  pointycastle: ^3.9.1
  redis: ^4.0.0
  teledart: ^0.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
